### ISSUE TITLE
Add public documentation for buildevents

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/buildevents#115]
**Is your feature request related to a problem? Please describe.**

Currently, in the main docs site, there is only a single link out to buildevents. This makes discovery hard.

**Describe the solution you'd like**

Document buildevents in the main docs site.

**Describe alternatives you've considered**

**Additional context**

**Comment by vreynolds** [comment]
https://docs.honeycomb.io/getting-data-in/integrations/ci-cd/buildevents/
