### ISSUE TITLE
Generate 8-byte span IDs to conform with OpenTelemetry spec (instead of 16-byte currently)

### ISSUE THREAD

**Issue by brentax** [honeycombio/buildevents#171]
Thank you for making this tool! It made it super easy to instrument our CircleCI builds and deploys.

**Is your feature request related to a problem? Please describe.**
_tl;dr of problem:_ `buildevents cmd` generates 16-byte span IDs, but [OpenTelemetry specifies](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spancontext) (and the [Python library implements](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/trace/span.py#L403)) an 8-byte limit for span IDs. This blocks us from connecting Python/OpenTelemetry spans to a buildevents trace.

_Longer version:_ I am using buildevents to instrument CircleCI workflows that call many Python scripts. I am using OpenTelemetry to instrument some of those Python scripts. I am trying to include the spans generated in the Python scripts as child spans to those generated by buildevents by using the `HONEYCOMB_TRACE` propagation data sent by `buildevents cmd`. buildevents is generating 16-byte span IDs, but OpenTelemetry only accepts 8-byte span IDs. I have been unable to figure out a way to set a root span in Python's OpenTelemetry implementation with the span IDs I get from buildevents.

**Describe the solution you'd like**
Ideally, buildevents would generate 8-byte span IDs to match the OpenTelemetry spec. I noticed the 16-byte IDs [happening here in `cmd_cmd.go`](https://github.com/honeycombio/buildevents/blob/main/cmd_cmd.go#L62), but it may be happening in other parts of the code.

**Describe alternatives you've considered**

- Don't include Python spans as children of the overall CircleCI workflow traces. This is what we'll be doing for now.
- Patch our own version of OpenTelemetry to allow larger Span IDs. I'd rather not incur the extra overhead of managing our own fork and keeping it updated with upstream.
- Patch our own version of buildevents to generate smaller Span IDs. Similar issue with the overhead. Plus we don't currently have any go code or build systems, so we'd also need to manage that.
- I'm open to other alternatives that we haven't considered yet, would love a workaround!

**Additional context**
I think I covered it all, but happy to answer any questions.

**Comment by JamieDanielson** [comment]
Thank you for providing this detail @brentax!

For implementing, it may be best to add a new boolean flag to enable 8-byte span IDs instead of 16-byte span IDs, to prevent breakage for current users while still allowing the 16-byte option for those who want it. We'll have to think a bit on this, and have added to our backlog.

**Comment by brentax** [comment]
Thanks @JamieDanielson!

A boolean flag would work well for our use case. I'll follow this issue for any updates.

**Comment by ham1** [comment]
Could we perhaps allow specifying the span id for each command, so that this and other use cases can be catered for?

**Comment by lizthegrey** [comment]
This is partially addressed with https://github.com/honeycombio/buildevents-orb/pull/110

**Comment by lizthegrey** [comment]
https://github.com/honeycombio/buildevents-orb/releases/tag/v0.12.0 It's now released.
