### ISSUE TITLE
[Feature request] Add support for GitHub Actions

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/buildevents#63]
Missing in the list of CI providers that are supported out of the box is GitHub Actions. It's a fairly new player, but it's quickly gaining a lot of adoption.
So I'd like to ask if you can add support for GitHub Actions as well.

The available environment variables are documented here: [Using environment variables](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables)
Most notably they use `GITHUB_ACTIONS` to indicate that the process is run within the GitHub Actions environment.

I've been able to pass these fields manually using the `BUILDEVENT_FILE`. But since I wasn't familiar with the logfmt format, this cost me more time that I would've liked.
Example: https://github.com/kvrhdn/tfe-run/blob/master/.github/workflows/integration.yaml#L27

**Comment by Vlaaaaaaad** [comment]
For background, @ceejbot also integrated `buildevents` with GitHub Actions, as per https://twitter.com/ceejbot/status/1252765536192094208 :
> The end (for now) results. The service@hash is a link to the commit. 
>
> The huge gap between the two deploys is clock skew because chrony wasn’t running, so hooray for Honeycomb build timings turning up a problem with our default AMI bake.
> ![EWK3m-lU0AIFXKe](https://user-images.githubusercontent.com/5440007/80303214-7cc0da80-87b7-11ea-88e8-ea6f8fc70894.jpeg)

The implementation was shared in a Gist: https://gist.github.com/ceejbot/a9cf6516ef19c84c22fd516ff3073f20 ❤️

**Comment by kvrhdn** [comment]
Thanks for the link @Vlaaaaaaad. My implementation is indeed based on the Gist @ceejbot shared.

**Comment by kvrhdn** [comment]
FYI, I have made a custom action which should simplify using buildevents in GitHub Actions. It will install buildevents, set some reasonable default fields (the branch, event,...) and ensures `buildevents build` is always called (it's a 'wrapping action').

You can find it here [kvrhdn/gha-buildevents](https://github.com/kvrhdn/gha-buildevents).

**Comment by kvrhdn** [comment]
This has been added with https://github.com/honeycombio/buildevents/pull/66 in the meantime 🙂
