### ISSUE TITLE
Make `buildevents cmd` NAME parameter optional

### ISSUE THREAD

**Issue by DavidS** [honeycombio/buildevents#71]
The name is hand if the command itself is not very expressive. In my pipeline I'd be fine with always just using the command itself as name for a cmd span. Instead I have to add a redundant name to each invocation.

**Comment by MikeGoldsmith** [comment]
Hey @DavidS - thank you for raising this issue and sorry for the delay in getting back to you. We're reviewing all our issues and can see this was never addressed.

If still relevant, please could you provide more context and detail on the issue you're experiencing and how you'd like to see it improve?

**Comment by DavidS** [comment]
Have a look at most of the invocations in my previous job's CI pipelines. e.g.: 
https://github.com/puppetlabs/puppetlabs-apache/blob/9fae75a087d575d10f411fb71ffcbaf5f04c652d/.github/workflows/nightly.yml#L128

**Comment by kentquirk** [comment]
We've finally evaluated this, and we believe that there's actually far more utility in leaving `name` as a low-cardinality field in most cases; when you're looking across a lot of builds, it's nice to be able to do things like `GROUP BY name` to see trends across common actions. Consequently, we won't be making this change. Sorry for the long process.
