### ISSUE TITLE
Add ability to override trace.parent_id

### ISSUE THREAD

**Issue by MarilynFranklin** [honeycombio/buildevents#75]
**What is the problem you're trying to solve**

I'm tracing builds on buildkite. When using the `step` command, I would like
the ability to change the `trace.parent_id` so that I can nest spans underneath
other spans so that the waterfall graph is easier to read.

I've tried setting the `trace.parent_id` in the `$BUILDEVENT_FILE`, but the
`step` command always sets `trace.parent_id` to the same value as the
`trace.trace_id` and doesn't allow me to override that value.  This makes sense
for children of the root trace, but does not allow for nested spans.

**Describe the solution you'd like**

I would like the ability to override the `trace.parent_id` by adding it to the
tags file:

```
BUILDEVENT_FILE=tags-list.txt
STEP_START=$(date +%s)
STEP_SPAN_ID=$(echo before_script | sum | cut -f 1 -d \ )
echo "trace.parent_id=${BUILDKITE_JOB_ID}" >> $BUILDEVENT_FILE
buildevents step $BUILDKITE_BUILD_ID $STEP_SPAN_ID $STEP_START name
```

**Comment by MikeGoldsmith** [comment]
Closing as #75 was merged and released as part of [v0.5.0](https://github.com/honeycombio/buildevents/releases/tag/v0.5.0).
