### ISSUE TITLE
Add a `quiet` flag

### ISSUE THREAD

**Issue by jesse-peters** [honeycombio/buildevents#79]
I ran into an issue when I was trying to use terraform and terragrunt with this tool. I have aliased terraform so that terragrunt calls the following command:

`buildevents cmd $CI_PIPELINE_ID $STEP_SPAN_ID $TF_NAME -- terraform "$@"`

This was tripping up terragrunt though, because it was adding extra information to the output:

e.g.
```running /bin/bash -c "terraform" "--version"```

I was able to get around it by piping the output to `awk '{if(NR>1)print}'`, but it would have been helpful if I could have used a `--quiet` flag.

**Comment by tybritten** [comment]
I'm submitting a PR for this shortly
